
version: '3.8'
name: glow-app-backend-dev

services:
  service:
    build: 
      context: .
      no_cache: true
      dockerfile: dockerfile
      args:
        NODE_ENV: 'development'
    container_name: service
    hostname: service
    ports:
      - 443:443
    env_file:
      - docker.env
    environment:
      - TZ=Asia/Amman
    volumes:
      - ./src/:/app/src/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: always
    depends_on:
      - redis
    networks:
      - glow-app-network

  redis:
      image: redis:latest
      container_name: redis
      hostname: redis
      restart: always
      ports:
          - '6379:6379'
      volumes:
          - redis_data:/data
      healthcheck:
        test: ['CMD', 'redis-cli', 'ping']
        interval: 10s
        timeout: 30s
        retries: 5
      networks:
        - glow-app-network


volumes:
  redis_data:

networks:
  glow-app-network:
    driver: bridge